import test, { after, before } from 'node:test';
import assert from 'node:assert/strict';
import { Prisma } from '@prisma/client';
import prisma from '../src/lib/prisma';
import { approveDeposit, approveWithdrawal, createDeposit, createWithdrawal, transferFunds } from '../src/lib/banking';

const P = `ledger_ci_${Date.now()}_`;
async function user(label: string) { return prisma.user.create({ data: { email: `${P}${label}@example.test`, passwordHash: 'test-only', firstName: label, lastName: 'Ledger', status: 'active' } }); }
async function account(userId: string, balance: string, type = 'CHECKING') { return prisma.account.create({ data: { userId, accountType: type, accountNumber: `${Date.now()}${Math.random().toString().slice(2, 9)}`.slice(0, 16), balance: new Prisma.Decimal(balance), availableBalance: new Prisma.Decimal(balance), currency: 'USD', status: 'active' } }); }
async function journal(type: string, id: string) { const rows = await prisma.$queryRaw<Array<{ id:string; status:string; total_debit:Prisma.Decimal; total_credit:Prisma.Decimal; entry_count:bigint; debit_sum:Prisma.Decimal; credit_sum:Prisma.Decimal }>>`SELECT j."id",j."status",j."total_debit",j."total_credit",COUNT(le."id") AS "entry_count",COALESCE(SUM(CASE WHEN le."direction"='DEBIT' THEN le."amount" ELSE 0 END),0) AS "debit_sum",COALESCE(SUM(CASE WHEN le."direction"='CREDIT' THEN le."amount" ELSE 0 END),0) AS "credit_sum" FROM "financial_journals" j LEFT JOIN "ledger_entries" le ON le."journal_id"=j."id" WHERE j."source_type"=${type} AND j."source_id"=${id} GROUP BY j."id"`; return rows[0]; }
async function balanced(type:string,id:string,amount:string){const j=await journal(type,id);assert.ok(j);assert.equal(j.status,'POSTED');assert.equal(Number(j.entry_count),2);assert.ok(j.debit_sum.eq(amount));assert.ok(j.credit_sum.eq(amount));assert.ok(j.total_debit.eq(amount));assert.ok(j.total_credit.eq(amount));return j;}
async function entryAccount(journalId:string,direction:'DEBIT'|'CREDIT'){const rows=await prisma.$queryRaw<Array<{account_id:string}>>`SELECT "account_id" FROM "ledger_entries" WHERE "journal_id"=${journalId} AND "direction"=${direction}`;assert.equal(rows.length,1);return rows[0].account_id;}

before(async()=>{await prisma.$queryRaw`SELECT 1`;});
after(async()=>{await prisma.$disconnect();});

test('persisted transfer creates one balanced journal',async()=>{const a=await user('sender'),b=await user('receiver');const source=await account(a.id,'1000'),destination=await account(b.id,'50');const r=await transferFunds(a.id,{senderAccountId:source.id,recipientAccountNumber:destination.accountNumber,amount:'100.00',idempotencyKey:`${P}transfer`},{});assert.equal((await prisma.account.findUniqueOrThrow({where:{id:source.id}})).balance.toString(),'900');assert.equal((await prisma.account.findUniqueOrThrow({where:{id:destination.id}})).balance.toString(),'150');const j=await balanced('TRANSFER',r.transfer.id,'100.00');assert.equal((await prisma.transaction.findMany({where:{journalId:j.id}})).length,2);});

test('persisted deposit debits the actual clearing ledger and credits customer',async()=>{const sys=await user('deposit_system'),customer=await user('deposit_customer');await account(sys.id,'1000','CLEARING');const target=await account(customer.id,'0');const dep=await createDeposit(customer.id,{accountId:target.id,amount:'100.00'});await approveDeposit(sys.id,dep.id);assert.equal((await prisma.deposit.findUniqueOrThrow({where:{id:dep.id}})).status,'completed');assert.equal((await prisma.account.findUniqueOrThrow({where:{id:target.id}})).balance.toString(),'100');const j=await balanced('DEPOSIT',dep.id,'100.00');const clearing=await prisma.account.findUniqueOrThrow({where:{id:await entryAccount(j.id,'DEBIT')}});assert.ok(clearing.balance.lt('1000'));});

test('duplicate deposit approval posts once',async()=>{const sys=await user('dup_system'),customer=await user('dup_customer');await account(sys.id,'500','CLEARING');const target=await account(customer.id,'0');const dep=await createDeposit(customer.id,{accountId:target.id,amount:'75.00'});await approveDeposit(sys.id,dep.id);await approveDeposit(sys.id,dep.id);const count=await prisma.$queryRaw<Array<{count:bigint}>>`SELECT COUNT(*) AS count FROM "financial_journals" WHERE "source_type"='DEPOSIT' AND "source_id"=${dep.id}`;assert.equal(Number(count[0].count),1);assert.equal((await prisma.account.findUniqueOrThrow({where:{id:target.id}})).balance.toString(),'75');});

test('persisted withdrawal debits customer and credits the actual clearing ledger',async()=>{const sys=await user('withdrawal_system'),customer=await user('withdrawal_customer');await account(sys.id,'0','CLEARING');const source=await account(customer.id,'1000');const w=await createWithdrawal(customer.id,{accountId:source.id,amount:'125.50',destination:'test'});await approveWithdrawal(sys.id,w.id);assert.equal((await prisma.withdrawal.findUniqueOrThrow({where:{id:w.id}})).status,'completed');assert.equal((await prisma.account.findUniqueOrThrow({where:{id:source.id}})).balance.toString(),'874.5');const j=await balanced('WITHDRAWAL',w.id,'125.50');const clearing=await prisma.account.findUniqueOrThrow({where:{id:await entryAccount(j.id,'CREDIT')}});assert.ok(clearing.balance.gte('125.5'));});

test('concurrent withdrawal approval produces at most one posting and never double-debits',async()=>{const sys=await user('conc_system'),customer=await user('conc_customer');await account(sys.id,'0','CLEARING');const source=await account(customer.id,'300');const w=await createWithdrawal(customer.id,{accountId:source.id,amount:'100.00',destination:'test'});const results=await Promise.allSettled([approveWithdrawal(sys.id,w.id),approveWithdrawal(sys.id,w.id)]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);const count=await prisma.$queryRaw<Array<{count:bigint}>>`SELECT COUNT(*) AS count FROM "financial_journals" WHERE "source_type"='WITHDRAWAL' AND "source_id"=${w.id}`;assert.equal(Number(count[0].count),1);assert.equal((await prisma.account.findUniqueOrThrow({where:{id:source.id}})).balance.toString(),'200');await balanced('WITHDRAWAL',w.id,'100.00');});

test('concurrent same-key transfers create one movement',async()=>{const a=await user('key_sender'),b=await user('key_receiver');const source=await account(a.id,'1000'),destination=await account(b.id,'0');const input={senderAccountId:source.id,recipientAccountNumber:destination.accountNumber,amount:'250.00',idempotencyKey:`${P}same-key`};const results=await Promise.allSettled([transferFunds(a.id,input,{}),transferFunds(a.id,input,{})]);const ok=results.filter((x):x is PromiseFulfilledResult<Awaited<ReturnType<typeof transferFunds>>>=>x.status==='fulfilled');assert.ok(ok.length>=1);const id=ok[0].value.transfer.id;assert.equal((await prisma.transfer.findMany({where:{idempotencyKey:input.idempotencyKey}})).length,1);assert.equal((await prisma.account.findUniqueOrThrow({where:{id:source.id}})).balance.toString(),'750');assert.equal((await prisma.account.findUniqueOrThrow({where:{id:destination.id}})).balance.toString(),'250');await balanced('TRANSFER',id,'250.00');});

test('concurrent transfers cannot overspend one account',async()=>{const a=await user('over_sender'),b=await user('over_a'),c=await user('over_b');const source=await account(a.id,'1000'),da=await account(b.id,'0'),db=await account(c.id,'0');const r=await Promise.allSettled([transferFunds(a.id,{senderAccountId:source.id,recipientAccountNumber:da.accountNumber,amount:'700.00',idempotencyKey:`${P}over-a`},{}),transferFunds(a.id,{senderAccountId:source.id,recipientAccountNumber:db.accountNumber,amount:'700.00',idempotencyKey:`${P}over-b`},{})]);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);const s=await prisma.account.findUniqueOrThrow({where:{id:source.id}});assert.equal(s.balance.toString(),'300');assert.ok(s.balance.gte(0));});

test('exact decimal amounts remain exact in persisted accounting',async()=>{const a=await user('precision_sender'),b=await user('precision_receiver');const source=await account(a.id,'1.00'),destination=await account(b.id,'0');const r=await transferFunds(a.id,{senderAccountId:source.id,recipientAccountNumber:destination.accountNumber,amount:'0.01',idempotencyKey:`${P}precision`},{});assert.equal((await prisma.account.findUniqueOrThrow({where:{id:source.id}})).balance.toString(),'0.99');assert.equal((await prisma.account.findUniqueOrThrow({where:{id:destination.id}})).balance.toString(),'0.01');await balanced('TRANSFER',r.transfer.id,'0.01');});

test('posted journals are globally balanced and every ledger entry has a parent',async()=>{const bad=await prisma.$queryRaw<Array<{id:string}>>`SELECT j."id" FROM "financial_journals" j LEFT JOIN "ledger_entries" le ON le."journal_id"=j."id" WHERE j."status"='POSTED' GROUP BY j."id",j."total_debit",j."total_credit" HAVING COUNT(le."id")<>2 OR COALESCE(SUM(CASE WHEN le."direction"='DEBIT' THEN le."amount" ELSE 0 END),0)<>j."total_debit" OR COALESCE(SUM(CASE WHEN le."direction"='CREDIT' THEN le."amount" ELSE 0 END),0)<>j."total_credit" OR j."total_debit"<>j."total_credit"`;assert.equal(bad.length,0);const orphan=await prisma.$queryRaw<Array<{id:string}>>`SELECT le."id" FROM "ledger_entries" le LEFT JOIN "financial_journals" j ON j."id"=le."journal_id" WHERE le."journal_id" IS NULL OR j."id" IS NULL LIMIT 1`;assert.equal(orphan.length,0);});
