'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import BankNav from '../../components/BankNav';

interface Account { id:string; accountType:string; accountNumber:string; balance:number|string; availableBalance:number|string; currency:string; status:string }
const money=(v:number|string,c='USD')=>new Intl.NumberFormat('en-US',{style:'currency',currency:c}).format(Number(v||0));
const title=(v:string)=>v.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());

export default function AccountsPage(){
  const [accounts,setAccounts]=useState<Account[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  useEffect(()=>{fetch('/api/v1/accounts').then(async r=>{const x=await r.json();if(!r.ok||!x.success)throw new Error(x.error||'Unable to load accounts');setAccounts(x.data||[])}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
  return <div className="min-h-screen bg-slate-50 pb-20 lg:pb-0"><BankNav/><main className="page-container lg:pl-[17rem]"><header><p className="text-sm font-medium text-indigo-700">Money</p><h1 className="mt-1 text-2xl font-bold tracking-tight sm:text-3xl">Accounts</h1><p className="mt-1 text-sm text-slate-500">View balances, account details, and recent activity.</p></header>{loading?<div className="mt-6 grid gap-4 md:grid-cols-2"><div className="h-48 animate-pulse rounded-2xl bg-slate-200"/><div className="h-48 animate-pulse rounded-2xl bg-slate-200"/></div>:error?<div className="mt-6 card"><p className="font-semibold">We couldn't load your accounts</p><p className="mt-1 text-sm text-slate-500">{error}</p></div>:<div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{accounts.map(a=><Link key={a.id} href={`/accounts/${a.id}`} className="group overflow-hidden rounded-2xl border bg-white shadow-sm transition hover:-translate-y-0.5 hover:border-indigo-200 hover:shadow-md"><div className="bg-slate-950 p-6 text-white"><div className="flex items-center justify-between"><span className="text-xs font-semibold uppercase tracking-widest text-slate-300">{title(a.accountType)}</span><span className="rounded-full bg-white/10 px-2.5 py-1 text-[11px] font-semibold">{title(a.status)}</span></div><p className="mt-8 text-3xl font-bold tracking-tight">{money(a.balance,a.currency)}</p><p className="mt-1 text-sm text-slate-400">Available {money(a.availableBalance,a.currency)}</p></div><div className="flex items-center justify-between p-5"><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Account number</p><p className="mt-1 text-sm font-semibold text-slate-800">•••• {a.accountNumber.slice(-4)}</p></div><span className="text-sm font-semibold text-indigo-700">View →</span></div></Link>)}{!accounts.length&&<div className="card col-span-full text-center"><p className="font-semibold text-slate-900">No accounts available</p><p className="mt-1 text-sm text-slate-500">Your accounts will appear here once they are opened.</p></div>}</div>}</main></div>;
}
