"use client"

import Link from "next/link"
import { FormEvent, useState } from "react"
import { ArrowLeft, MailCheck } from "lucide-react"

export default function ForgotPasswordPage() {
  const [email, setEmail] = useState(""); const [sent, setSent] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState("")
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); try { const response = await fetch("/api/auth", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "request-password-reset", email }) }); if (!response.ok) throw new Error("We could not process that request."); setSent(true) } catch (cause) { setError(cause instanceof Error ? cause.message : "Try again shortly") } finally { setLoading(false) } }
  return <main className="flex min-h-screen items-center justify-center bg-[#f6f8fb] px-6 py-12 text-[#10233f]"><div className="w-full max-w-md"><Link href="/login" className="mb-10 inline-flex items-center gap-2 text-sm text-[#52627a] hover:text-[#10233f]"><ArrowLeft className="size-4" /> Back to sign in</Link><div className="rounded-[2rem] border border-[#dce4ee] bg-white p-7 shadow-xl shadow-[#10233f]/5 sm:p-10"><div className="flex size-12 items-center justify-center rounded-2xl bg-[#10233f] text-white"><MailCheck className="size-5" /></div><p className="mt-7 text-sm font-medium text-[#b88b43]">Account recovery</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Forgot your password?</h1>{sent ? <div className="mt-5 rounded-xl bg-[#f4f7fa] p-4 text-sm leading-6 text-[#52627a]">If an account exists for <strong className="text-[#10233f]">{email}</strong>, a secure reset link will arrive shortly. The link expires in 30 minutes.</div> : <><p className="mt-3 leading-7 text-[#52627a]">Enter your email and we&apos;ll send a secure link to create a new password.</p>{error && <p role="alert" className="mt-5 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<form onSubmit={submit} className="mt-7 flex flex-col gap-4"><label className="flex flex-col gap-2 text-sm font-medium">Email address<input className="h-12 rounded-xl border border-[#cbd6e3] px-4 outline-none focus:border-[#b88b43] focus:ring-2 focus:ring-[#b88b43]/20" type="email" autoComplete="email" required value={email} onChange={(event) => setEmail(event.target.value)} /></label><button disabled={loading} className="h-12 rounded-xl bg-[#10233f] font-medium text-white hover:bg-[#1b365c] disabled:opacity-60">{loading ? "Sending secure link..." : "Send reset link"}</button></form></>}<p className="mt-7 text-center text-sm text-[#52627a]"><Link href="/login" className="font-semibold text-[#8a642d] hover:underline">Return to sign in</Link></p></div></div></main>
}
