'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';

type Row = Record<string, unknown>;
type ModuleSpec = { title: string; description: string; group: string; resource?: string; fields: string[]; actions: string[] };

export const ADMIN_MODULES: Record<string, ModuleSpec> = {
  users:{title:'Users',description:'Customer identity, lifecycle and access management.',group:'Overview & People',resource:'users',fields:['firstName','lastName','email','status','kycStatus','createdAt'],actions:['View','Review']},
  customers:{title:'Customers',description:'Master customer roster with account and KYC context.',group:'Overview & People',resource:'customers',fields:['firstName','lastName','email','kycStatus','status','createdAt'],actions:['View','Review KYC']},
  kyc:{title:'KYC',description:'Identity verification queue and review workspace.',group:'Overview & People',fields:['customer','document','verificationStatus','reviewerId','reviewedAt','createdAt'],actions:['Open','Approve','Reject','Request resubmission']},
  leads:{title:'Leads',description:'Prospect pipeline, onboarding and follow-up operations.',group:'Overview & People',fields:['name','email','source','status','assignedTo','followUpAt'],actions:['Create','Assign','Convert']},
  tasks:{title:'Tasks',description:'Staff work queue, assignments and operational follow-up.',group:'Overview & People',fields:['title','priority','status','assignee','dueDate','createdAt'],actions:['Create','Assign','Complete']},
  referrals:{title:'Referrals',description:'Referral attribution, commissions and relationship tracking.',group:'Overview & People',fields:['referralCode','customer','referredCustomer','commission','status','createdAt'],actions:['View tree','Review']},
  import:{title:'Import',description:'Controlled CSV ingestion with validation and duplicate detection.',group:'Overview & People',fields:['file','mapping','records','valid','duplicates','errors'],actions:['Upload CSV','Validate','Import']},
  deposits:{title:'Deposits',description:'Incoming-funds review and approval queue.',group:'Money & Financial Ledger',resource:'deposits',fields:['customer','account','amount','currency','reference','status','createdAt'],actions:['Review','Approve','Reject']},
  withdrawals:{title:'Withdrawals',description:'Outbound payout review, holds and completion tracking.',group:'Money & Financial Ledger',resource:'withdrawals',fields:['customer','account','amount','currency','destination','status','createdAt'],actions:['Review','Approve','Reject','Hold']},
  transfers:{title:'Transfers',description:'Internal account-to-account transfer monitoring.',group:'Money & Financial Ledger',resource:'transfers',fields:['reference','senderUserId','recipientUserId','amount','currency','status','createdAt'],actions:['View','Audit trail']},
  transactions:{title:'Transactions',description:'Financial activity, references and ledger review.',group:'Money & Financial Ledger',resource:'transactions',fields:['txType','amount','currency','status','referenceId','createdAt'],actions:['View','Audit trail']},
  accounts:{title:'Accounts',description:'Customer accounts, balances, ownership and status.',group:'Money & Financial Ledger',resource:'accounts',fields:['accountNumber','accountType','currency','balance','availableBalance','status','openedAt'],actions:['View','Activity']},
  'payment-methods':{title:'Payment Methods',description:'Payment rails, wire instructions and operational configuration.',group:'Money & Financial Ledger',fields:['name','type','currency','status','instructions','updatedAt'],actions:['Add','Edit','Disable']},
  cards:{title:'Cards',description:'Virtual and physical card inventory with secure controls.',group:'Money & Financial Ledger',fields:['cardholder','lastFour','cardType','status','spendingLimitDaily','spendingLimitMonthly'],actions:['View','Freeze','Activate','Replace']},
  'card-setup':{title:'Card Setup',description:'Card product and issuance configuration.',group:'Money & Financial Ledger',fields:['product','network','type','dailyLimit','monthlyLimit','status'],actions:['Create','Edit']},
  currencies:{title:'Currencies',description:'Supported currencies, precision and exchange-rate controls.',group:'Money & Financial Ledger',fields:['code','symbol','decimals','baseCurrency','rate','status','updatedAt'],actions:['Add','Update rate','Disable']},
  loans:{title:'Loans',description:'Loan applications, approvals, disbursements and servicing.',group:'Money & Financial Ledger',fields:['customer','principal','rate','duration','status','outstandingBalance'],actions:['Review','Approve','Reject','Disburse']},
  grants:{title:'Grants',description:'Grant eligibility, approval and issuance operations.',group:'Money & Financial Ledger',fields:['name','customer','amount','currency','status','expiresAt'],actions:['Create','Approve','Issue']},
  irs:{title:'Compliance / Tax',description:'Tax-document status, compliance holds and review notes.',group:'Money & Financial Ledger',fields:['customer','documentStatus','withholdingStatus','holdStatus','reviewer','updatedAt'],actions:['Open','Place hold','Release hold','Notify']},
  membership:{title:'Membership',description:'Membership tiers, benefits, pricing and assignments.',group:'Money & Financial Ledger',fields:['tier','price','benefits','eligibility','status','updatedAt'],actions:['Create','Edit','Assign']},
  plans:{title:'Plans',description:'Product plans with duration, limits, disclosures and eligibility.',group:'Trading & Engagement',fields:['name','description','duration','minimum','maximum','riskDisclosure','status'],actions:['Create','Edit','Publish']},
  crypto:{title:'Crypto',description:'Asset, network and operational configuration.',group:'Trading & Engagement',fields:['asset','network','pair','depositStatus','withdrawalStatus','confirmations'],actions:['Add asset','Configure','Disable']},
  signals:{title:'Signals',description:'Signal sources, publishing state and health monitoring.',group:'Trading & Engagement',fields:['source','symbol','direction','status','publishedAt','provider'],actions:['Create','Publish','Disable']},
  providers:{title:'Providers',description:'Integration health, configuration and provider status.',group:'Trading & Engagement',fields:['name','type','environment','status','lastCheck','errorRate'],actions:['Configure','Test','Disable']},
  'copy-trading':{title:'Copy Trading',description:'Master traders, followers, allocation and risk controls.',group:'Trading & Engagement',fields:['master','follower','allocation','riskLimit','status','createdAt'],actions:['View','Adjust risk','Suspend']},
  courses:{title:'Courses',description:'Educational courses, modules, lessons and publishing.',group:'Trading & Engagement',fields:['title','modules','lessons','students','status','updatedAt'],actions:['Create','Edit','Publish']},
  inbox:{title:'Inbox',description:'Unified customer communications and staff workflow.',group:'Trading & Engagement',fields:['customer','subject','channel','priority','status','updatedAt'],actions:['Open','Assign','Resolve']},
  tickets:{title:'Tickets',description:'Support queue, assignments, SLA and resolution.',group:'Trading & Engagement',fields:['ticket','customer','priority','assignee','status','updatedAt'],actions:['Open','Assign','Resolve','Reopen']},
  'live-chat':{title:'Live Chat',description:'Active customer conversations and agent assignment.',group:'Trading & Engagement',fields:['conversation','customer','agent','status','lastMessage','updatedAt'],actions:['Open','Assign','Close']},
  contact:{title:'Contact',description:'Inbound contact requests and response workflow.',group:'Trading & Engagement',fields:['name','email','subject','status','assignedTo','createdAt'],actions:['Open','Assign','Resolve']},
  broadcast:{title:'Broadcast',description:'Controlled customer communications with audience safeguards.',group:'Trading & Engagement',fields:['title','channel','audience','status','scheduledAt','createdAt'],actions:['Draft','Preview','Schedule','Cancel']},
  agents:{title:'Agents',description:'Staff accounts, roles, permissions and activity.',group:'Trading & Engagement',fields:['name','email','role','status','mfa','lastLogin'],actions:['View','Change role','Deactivate']},
  testimonials:{title:'Testimonials',description:'Customer testimonial moderation and publishing.',group:'Trading & Engagement',fields:['customer','quote','status','publishedAt','order'],actions:['Review','Approve','Reject','Unpublish']},
  appearance:{title:'Appearance',description:'Brand colors, typography, layout and accessibility settings.',group:'Site & System Configuration',fields:['brand','primaryColor','font','radius','navigation','updatedAt'],actions:['Save','Preview']},
  themes:{title:'Themes',description:'Light/dark theme and accessible visual presets.',group:'Site & System Configuration',fields:['name','mode','contrast','accent','status','updatedAt'],actions:['Create','Activate','Duplicate']},
  assets:{title:'Assets',description:'Logo, favicon, images and document asset management.',group:'Site & System Configuration',fields:['name','type','size','mime','visibility','createdAt'],actions:['Upload','Replace','Archive']},
  content:{title:'Content',description:'Landing-page, legal and public-site content management.',group:'Site & System Configuration',fields:['section','title','status','version','updatedBy','updatedAt'],actions:['Edit','Preview','Publish','Rollback']},
  faq:{title:'FAQ',description:'Knowledge-base categories, articles and publishing workflow.',group:'Site & System Configuration',fields:['question','category','status','order','updatedAt'],actions:['Create','Edit','Publish','Reorder']},
  'audit-logs':{title:'Audit Log',description:'Append-only security, staff and data-mutation history.',group:'Site & System Configuration',resource:'audit-logs',fields:['actorId','actorType','action','entityType','entityId','ipAddress','createdAt'],actions:['Inspect','Export']},
  roles:{title:'Roles & Permissions',description:'Administrative roles and permission assignments.',group:'Site & System Configuration',fields:['role','permissions','members','status','updatedAt'],actions:['Create role','Edit permissions']},
  settings:{title:'Settings',description:'Protected platform configuration with masked sensitive values.',group:'Site & System Configuration',fields:['setting','category','value','visibility','updatedAt'],actions:['Edit setting','Review changes']},
};

function display(value: unknown, key: string) {
  if (value === null || value === undefined || value === '') return '—';
  if (['amount','balance','limit','price','principal','minimum','maximum','commission','rate'].some(x => key.toLowerCase().includes(x))) { const n=Number(value); if(Number.isFinite(n)) return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n); }
  if (key.endsWith('At') || ['createdAt','updatedAt','openedAt','lastLogin'].includes(key)) { const d=new Date(String(value)); if(!Number.isNaN(d.getTime())) return d.toLocaleString(); }
  if (typeof value === 'object') return JSON.stringify(value);
  return String(value);
}

export default function AdminModuleWorkspace({ module }: { module: string }) {
  const spec = ADMIN_MODULES[module] || {title:module.replace(/-/g,' '),description:'Administration workspace.',group:'Administration',fields:['status','updatedAt'],actions:['Refresh']} as ModuleSpec;
  const [rows,setRows]=useState<Row[]>([]); const [q,setQ]=useState(''); const [loading,setLoading]=useState(Boolean(spec.resource)); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [view,setView]=useState<'table'|'cards'>('table');
  const load=useCallback(async()=>{ if(!spec.resource)return; setLoading(true);setError('');try{const r=await fetch(`/api/v1/admin/resources/${spec.resource}?q=${encodeURIComponent(q)}`,{cache:'no-store'});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.error||'Unable to load records');setRows(Array.isArray(j.data)?j.data:[]);}catch(e){setError(e instanceof Error?e.message:'Unable to load records')}finally{setLoading(false)}},[spec.resource,q]);
  useEffect(()=>{load()},[load]);
  const action=(label:string)=>setNotice(`${label} is available through the protected server-side workflow. No record was changed by the interface preview.`);
  const stats=useMemo(()=>[{label:'Records',value:String(rows.length)},{label:'Data source',value:spec.resource?'PostgreSQL':'Configured workspace'},{label:'Authorization',value:'Server-side'}],[rows.length,spec.resource]);
  return <main className="space-y-6">
    <div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div className="min-w-0 pl-10 sm:pl-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-indigo-400">{spec.group}</p><h1 className="mt-1 text-3xl font-bold capitalize tracking-tight text-white">{spec.title}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">{spec.description}</p></div><div className="flex flex-wrap gap-2">{spec.actions.slice(0,4).map(a=><button key={a} type="button" onClick={()=>action(a)} className="rounded-xl border border-white/10 bg-white/[.04] px-4 py-2.5 text-sm font-semibold text-slate-200 hover:bg-white/[.08]">{a}</button>)}</div></div>
    <div className="grid gap-3 sm:grid-cols-3">{stats.map(s=><div key={s.label} className="rounded-2xl border border-white/10 bg-slate-900/80 p-4"><p className="text-xs uppercase tracking-wider text-slate-500">{s.label}</p><p className="mt-2 text-xl font-semibold text-white">{s.value}</p></div>)}</div>
    {notice&&<div role="status" className="rounded-xl border border-amber-400/20 bg-amber-400/10 px-4 py-3 text-sm text-amber-200">{notice}</div>}
    <section className="overflow-hidden rounded-2xl border border-white/10 bg-slate-900/80 shadow-xl"><div className="flex flex-col gap-3 border-b border-white/10 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-2"><button onClick={()=>setView('table')} className={`rounded-lg px-3 py-2 text-xs font-semibold ${view==='table'?'bg-indigo-600 text-white':'text-slate-400 hover:bg-white/5'}`}>Table</button><button onClick={()=>setView('cards')} className={`rounded-lg px-3 py-2 text-xs font-semibold ${view==='cards'?'bg-indigo-600 text-white':'text-slate-400 hover:bg-white/5'}`}>Cards</button></div>{spec.resource&&<form onSubmit={e=>{e.preventDefault();load()}} className="flex gap-2"><input aria-label="Search" value={q} onChange={e=>setQ(e.target.value)} placeholder={`Search ${spec.title.toLowerCase()}`} className="min-h-10 w-full rounded-xl border border-white/10 bg-white/[.04] px-3 text-sm text-white outline-none placeholder:text-slate-600 focus:border-indigo-400 sm:w-72"/><button className="rounded-xl bg-indigo-600 px-4 text-sm font-semibold text-white">Search</button></form>}</div>
      {error&&<div role="alert" className="border-b border-red-500/20 bg-red-500/10 px-5 py-3 text-sm text-red-200">{error}</div>}
      {loading?<div className="space-y-3 p-5">{[1,2,3,4,5].map(n=><div key={n} className="h-12 animate-pulse rounded-xl bg-white/[.04]"/>)}</div>:rows.length===0?<div className="p-12 text-center"><p className="font-semibold text-slate-200">No data available</p><p className="mx-auto mt-1 max-w-lg text-sm leading-6 text-slate-500">No production records are being fabricated. This workspace uses the existing backend where a resource endpoint is available.</p></div>:view==='cards'?<div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-3">{rows.map((row,i)=><article key={String(row.id||row.reference||i)} className="rounded-xl border border-white/10 bg-white/[.025] p-4"><div className="flex items-start justify-between gap-3"><p className="font-semibold text-white">{display(row[spec.fields[0]],spec.fields[0])}</p><span className="rounded-full bg-white/[.06] px-2 py-1 text-[10px] text-slate-400">{display(row.status,'status')}</span></div><div className="mt-4 space-y-2">{spec.fields.slice(1,6).map(k=><div key={k} className="flex justify-between gap-4 text-xs"><span className="text-slate-500">{k.replace(/[A-Z]/g,' $&')}</span><span className="max-w-[60%] truncate text-right text-slate-300">{display(row[k],k)}</span></div>)}</div></article>)}</div>:<div className="overflow-x-auto"><table className="min-w-[900px] w-full text-left"><thead><tr className="border-b border-white/10">{spec.fields.map(c=><th key={c} className="px-5 py-3 text-[11px] font-bold uppercase tracking-wider text-slate-500">{c.replace(/[A-Z]/g,' $&')}</th>)}<th className="px-5 py-3 text-[11px] font-bold uppercase tracking-wider text-slate-500">Actions</th></tr></thead><tbody>{rows.map((row,i)=><tr key={String(row.id||row.reference||i)} className="border-b border-white/5 last:border-0 hover:bg-white/[.025]">{spec.fields.map(c=><td key={c} className="max-w-[260px] truncate px-5 py-4 text-sm text-slate-300">{display(row[c],c)}</td>)}<td className="px-5 py-4"><button onClick={()=>action('Inspect')} className="rounded-lg border border-white/10 px-3 py-2 text-xs font-semibold text-slate-300 hover:bg-white/5">Inspect</button></td></tr>)}</tbody></table></div>}
    </section>
    <div className="flex flex-wrap gap-2 text-xs text-slate-500"><Link href="/admin/dashboard" className="rounded-lg border border-white/10 px-3 py-2 hover:bg-white/5 hover:text-slate-300">← Overview</Link>{spec.resource&&<button onClick={load} className="rounded-lg border border-white/10 px-3 py-2 hover:bg-white/5 hover:text-slate-300">Refresh</button>}</div>
  </main>;
}
