"use client"

import Link from "next/link"
import { FormEvent, useState } from "react"
import { useSearchParams } from "next/navigation"

export default function ResetPasswordPage() {
  const searchParams = useSearchParams(); const email = searchParams.get("email") || ""; const token = searchParams.get("token") || ""; const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); if (password !== confirm) { setError("Passwords do not match."); return }; setLoading(true); setError(""); try { const response = await fetch("/api/auth", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "reset-password", email, token, password }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to reset password"); setMessage(data.message) } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to reset password") } finally { setLoading(false) } }
  return <main className="flex min-h-screen items-center justify-center bg-[#f6f8fb] px-6 py-12 text-[#10233f]"><div className="w-full max-w-md rounded-[2rem] border border-[#dce4ee] bg-white p-7 shadow-xl shadow-[#10233f]/5 sm:p-10"><p className="text-sm font-medium text-[#b88b43]">Crestline Capital</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Create a new password</h1>{message ? <><p className="mt-4 rounded-xl bg-emerald-50 p-4 text-sm leading-6 text-emerald-800">{message}</p><Link href="/login" className="mt-6 inline-flex h-12 w-full items-center justify-center rounded-xl bg-[#10233f] font-medium text-white">Continue to sign in</Link></> : <form onSubmit={submit} className="mt-7 flex flex-col gap-4"><label className="flex flex-col gap-2 text-sm font-medium">New password<input className="h-12 rounded-xl border border-[#cbd6e3] px-4 outline-none focus:border-[#b88b43] focus:ring-2 focus:ring-[#b88b43]/20" type="password" autoComplete="new-password" required minLength={8} value={password} onChange={(event) => setPassword(event.target.value)} /></label><label className="flex flex-col gap-2 text-sm font-medium">Confirm password<input className="h-12 rounded-xl border border-[#cbd6e3] px-4 outline-none focus:border-[#b88b43] focus:ring-2 focus:ring-[#b88b43]/20" type="password" autoComplete="new-password" required minLength={8} value={confirm} onChange={(event) => setConfirm(event.target.value)} /></label>{error && <p role="alert" className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<button disabled={loading || !email || !token} className="h-12 rounded-xl bg-[#10233f] font-medium text-white hover:bg-[#1b365c] disabled:opacity-60">{loading ? "Updating password..." : "Update password"}</button></form>}<p className="mt-7 text-center text-sm text-[#52627a]"><Link href="/login" className="font-semibold text-[#8a642d] hover:underline">Back to sign in</Link></p></div></main>
}
