'use client';

import { useEffect, useState } from 'react';
import BankNav from '../../components/BankNav';

const fields=[['firstName','First name'],['lastName','Last name'],['phone','Phone'],['addressLine1','Address'],['addressLine2','Address line 2'],['city','City'],['state','State'],['zipCode','ZIP code'],['country','Country']];
export default function Profile(){
 const [p,setP]=useState<any>({}); const [msg,setMsg]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [loading,setLoading]=useState(true);
 useEffect(()=>{fetch('/api/v1/profile').then(async r=>{const x=await r.json();if(!r.ok||!x.success)throw new Error(x.error||'Unable to load profile');setP(x.data||{})}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 async function save(e:any){e.preventDefault();setBusy(true);setMsg('');setError('');const body:any={};fields.forEach(([k])=>body[k]=p[k]||'');try{const r=await fetch('/api/v1/profile',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const x=await r.json();if(!r.ok||!x.success)throw new Error(x.error||'Update failed');setP((v:any)=>({...v,...x.data}));setMsg('Profile updated successfully.')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <div className="min-h-screen bg-slate-50 pb-20 lg:pb-0"><BankNav/><main className="page-container max-w-4xl lg:pl-[17rem]"><header><p className="text-sm font-medium text-indigo-700">Account</p><h1 className="mt-1 text-2xl font-bold tracking-tight sm:text-3xl">Profile</h1><p className="mt-1 text-sm text-slate-500">Manage your personal information and preferences.</p></header>{loading?<div className="mt-6 card animate-pulse space-y-4"><div className="h-8 w-48 rounded bg-slate-200"/><div className="h-11 rounded bg-slate-100"/><div className="h-11 rounded bg-slate-100"/></div>:<><section className="mt-6 card"><div className="flex items-center justify-between gap-4 border-b pb-5"><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Email</p><p className="mt-1 font-semibold text-slate-900">{p.email||'—'}</p></div><span className="rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-semibold text-emerald-700">Account {p.status||'active'}</span></div><form onSubmit={save} className="mt-6 grid gap-4 sm:grid-cols-2">{fields.map(([k,l])=><label key={k} className="label-text">{l}<input value={p[k]||''} onChange={e=>setP({...p,[k]:e.target.value})} className="input-field mt-1" autoComplete={k}/></label>)}<div className="sm:col-span-2 flex flex-col gap-3 border-t pt-5 sm:flex-row sm:items-center"><button disabled={busy} className="btn-primary">{busy?'Saving…':'Save changes'}</button>{msg&&<span role="status" className="text-sm font-medium text-emerald-700">{msg}</span>}{error&&<span role="alert" className="text-sm font-medium text-red-700">{error}</span>}</div></form></section><section className="mt-4 grid gap-4 sm:grid-cols-3"><div className="stat-card"><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">KYC status</p><p className="mt-2 font-semibold text-slate-900">{p.kycStatus||'—'}</p></div><div className="stat-card"><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">KYC tier</p><p className="mt-2 font-semibold text-slate-900">{p.kycTier??'—'}</p></div><div className="stat-card"><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Two-factor authentication</p><p className="mt-2 font-semibold text-slate-900">{p.totpEnabled?'Enabled':'Not enabled'}</p></div></section></>}</main></div>;
}
