'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import BankNav from '../../components/BankNav';
import { isCreditTransaction } from '../../lib/transaction-display';

interface Transaction { id:string; txType:string; amount:number|string; currency:string; description?:string|null; merchantName?:string|null; status:string; createdAt:string; referenceId?:string|null }
const money=(v:number|string,c='USD')=>new Intl.NumberFormat('en-US',{style:'currency',currency:c}).format(Number(v||0));
const title=(v:string)=>v.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const statuses=['ALL','completed','pending','failed','reversed','cancelled'];
const types=['ALL','TRANSFER','DEPOSIT','WITHDRAWAL','PAYMENT'];

export default function TransactionsPage(){
 const [items,setItems]=useState<Transaction[]>([]),[total,setTotal]=useState(0),[q,setQ]=useState(''),[type,setType]=useState('ALL'),[status,setStatus]=useState('ALL'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[skip,setSkip]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const limit=25;
 useEffect(()=>{setLoading(true);setError('');const p=new URLSearchParams({limit:String(limit),skip:String(skip)});if(q)p.set('q',q);if(type!=='ALL')p.set('type',type);if(status!=='ALL')p.set('status',status);if(from)p.set('from',from);if(to)p.set('to',to);fetch('/api/v1/transactions?'+p).then(async r=>{const x=await r.json();if(!r.ok||!x.success)throw new Error(x.error||'Unable to load transactions');setItems(x.data?.items||[]);setTotal(x.data?.total||0)}).catch(e=>setError(e instanceof Error?e.message:'Unable to load transactions')).finally(()=>setLoading(false))},[q,type,status,from,to,skip]);
 const reset=()=>{setQ('');setType('ALL');setStatus('ALL');setFrom('');setTo('');setSkip(0)};
 return <div className="min-h-screen bg-[#f6f5f2] pb-20 lg:pb-0"><BankNav/><main className="page-container lg:pl-[17rem]">
  <header><p className="text-xs font-bold uppercase tracking-[.16em] text-red-700">Money movement</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">Transactions</h1><p className="mt-1 text-sm text-slate-500">Review your Crestline Capital account activity.</p></header>
  <section className="mt-6 rounded-2xl border border-slate-300 bg-white p-4 shadow-sm sm:p-5"><div className="mb-4 flex items-center justify-between gap-3"><div><h2 className="font-bold text-slate-950">Activity search</h2><p className="text-xs text-slate-500">Find transfers, withdrawals, deposits and other activity.</p></div><button type="button" className="btn-secondary hidden sm:inline-flex" onClick={reset}>Clear filters</button></div>
   <div className="grid gap-3 md:grid-cols-[1fr_180px_180px]"><input className="input-field" value={q} onChange={e=>{setQ(e.target.value);setSkip(0)}} placeholder="Search references or merchants" aria-label="Search transactions"/><select className="input-field" value={type} onChange={e=>{setType(e.target.value);setSkip(0)}} aria-label="Transaction type">{types.map(x=><option key={x} value={x}>{x==='ALL'?'All types':title(x)}</option>)}</select><select className="input-field" value={status} onChange={e=>{setStatus(e.target.value);setSkip(0)}} aria-label="Transaction status">{statuses.map(x=><option key={x} value={x}>{x==='ALL'?'All statuses':title(x)}</option>)}</select></div>
   <div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-[1fr_1fr_auto]"><label className="text-xs font-semibold text-slate-500">From<input type="date" className="input-field mt-1" value={from} onChange={e=>{setFrom(e.target.value);setSkip(0)}}/></label><label className="text-xs font-semibold text-slate-500">To<input type="date" className="input-field mt-1" value={to} onChange={e=>{setTo(e.target.value);setSkip(0)}}/></label><button type="button" className="btn-secondary self-end sm:hidden" onClick={reset}>Clear filters</button></div>
  </section>
  <section className="mt-5 overflow-hidden rounded-2xl border border-slate-300 bg-white shadow-sm" aria-live="polite">
   {loading?<div className="space-y-3 p-5">{[1,2,3,4].map(i=><div key={i} className="h-16 animate-pulse rounded-xl bg-stone-100" aria-hidden="true"/>)}</div>:error?<div className="p-8 text-center"><p className="font-semibold text-slate-950">We could not load transactions</p><p className="mt-1 text-sm text-slate-500">{error}</p><button type="button" className="btn-primary mt-4" onClick={()=>setSkip(skip)}>Try again</button></div>:items.length?items.map(t=><Link href={`/transactions/${t.id}`} key={t.id} className="group flex min-h-16 items-center justify-between gap-4 border-b border-slate-200 p-4 last:border-0 hover:bg-stone-50 sm:p-5"><div className="flex min-w-0 items-center gap-3"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-full font-bold ${isCreditTransaction(t.txType)?'bg-emerald-50 text-emerald-700':'bg-stone-100 text-slate-700'}`} aria-hidden="true">{isCreditTransaction(t.txType)?'+':'−'}</span><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-950">{t.merchantName||t.description||title(t.txType)}</p><p className="mt-0.5 truncate text-xs text-slate-500">{new Date(t.createdAt).toLocaleString()} · {title(t.status)}</p></div></div><div className="shrink-0 text-right"><p className={`text-sm font-bold ${isCreditTransaction(t.txType)?'text-emerald-700':'text-slate-950'}`}>{isCreditTransaction(t.txType)?'+':'−'}{money(t.amount,t.currency)}</p><p className="mt-0.5 max-w-36 truncate text-xs text-slate-400">{t.referenceId||'No reference'}</p></div></Link>):<div className="p-10 text-center"><p className="font-semibold text-slate-950">No matching transactions</p><p className="mt-1 text-sm text-slate-500">Try changing your filters or date range.</p></div>}
  </section>
  <div className="mt-4 flex items-center justify-between text-sm text-slate-500"><span>{total?`${skip+1}–${Math.min(skip+items.length,total)} of ${total}`:'0 results'}</span><div className="flex gap-2"><button type="button" className="btn-secondary px-4" disabled={skip===0||loading} onClick={()=>setSkip(Math.max(0,skip-limit))}>Previous</button><button type="button" className="btn-secondary px-4" disabled={skip+items.length>=total||loading} onClick={()=>setSkip(skip+limit)}>Next</button></div></div>
 </main></div>;
}