'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';

type Deposit = { id:string; amount:string|number; currency:string; reference:string; status:string; createdAt:string; user:{firstName:string;lastName:string;email:string}; account:{accountNumber:string;currency:string} };
export default function AdminDepositsPage(){
 const [items,setItems]=useState<Deposit[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null);
 const load=async()=>{setLoading(true);try{const r=await fetch('/api/v1/admin/deposits');const j=await r.json();if(j.success)setItems(j.data)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const act=async(id:string,action:'approve'|'reject')=>{setBusy(id);try{const r=await fetch('/api/v1/admin/deposits',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id,action})});const j=await r.json();if(!j.success)alert(j.error||'Operation failed');await load()}finally{setBusy(null)}};
 return <div className="min-h-screen bg-gray-950 text-white"><header className="border-b border-gray-800 bg-gray-900"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4"><Link href="/admin/dashboard" className="font-bold text-xl">Crestline Capital · Admin</Link><nav className="flex gap-4 text-sm text-gray-400"><Link href="/admin/dashboard">Dashboard</Link><Link href="/admin/users">Users</Link><Link href="/admin/withdrawals">Withdrawals</Link><span className="text-white">Deposits</span></nav></div></header><main className="mx-auto max-w-7xl px-4 py-8"><div className="mb-6"><h1 className="text-2xl font-semibold">Deposit Review</h1><p className="mt-1 text-gray-400">Review pending customer deposit requests.</p></div>{loading?<div className="py-16 text-center text-gray-400">Loading deposits…</div>:<div className="overflow-x-auto rounded-xl border border-gray-800 bg-gray-900"><table className="w-full text-sm"><thead className="border-b border-gray-800 text-left text-gray-400"><tr><th className="p-4">Customer</th><th className="p-4">Account</th><th className="p-4">Amount</th><th className="p-4">Reference</th><th className="p-4">Status</th><th className="p-4">Action</th></tr></thead><tbody className="divide-y divide-gray-800">{items.map(d=><tr key={d.id}><td className="p-4"><div>{d.user.firstName} {d.user.lastName}</div><div className="text-gray-500">{d.user.email}</div></td><td className="p-4 font-mono">••••{d.account.accountNumber.slice(-4)}</td><td className="p-4">${Number(d.amount).toFixed(2)} {d.currency}</td><td className="p-4 font-mono text-xs">{d.reference}</td><td className="p-4"><span className="rounded-full bg-gray-800 px-2.5 py-1 text-xs">{d.status}</span></td><td className="p-4">{d.status==='pending'?<div className="flex gap-2"><button disabled={busy===d.id} onClick={()=>act(d.id,'approve')} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs disabled:opacity-50">Approve</button><button disabled={busy===d.id} onClick={()=>act(d.id,'reject')} className="rounded-lg bg-red-600 px-3 py-2 text-xs disabled:opacity-50">Reject</button></div>:<span className="text-gray-500">No action</span>}</td></tr>)}{items.length===0&&<tr><td colSpan={6} className="p-12 text-center text-gray-500">No deposits found.</td></tr>}</tbody></table></div>}</main></div>;
}
