'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';

type Account={id:string;accountType:string;accountNumber:string;routingNumber:string;balance:string|number;availableBalance:string|number;currency:string;status:string;interestRate:string|number|null;openedAt:string};
type Customer={id:string;email:string;firstName:string;lastName:string;status:string;transferBlocked:boolean;transferBlockMessage:string|null;withdrawalBlocked:boolean;withdrawalBlockMessage:string|null;accounts:Account[];kycStatus:string;kycTier:number;phone:string|null;country:string|null;city:string|null;state:string|null;zipCode:string|null;createdAt:string;totpEnabled:boolean;sms2faEnabled:boolean;bnkTag:string|null;_count:{transactions:number;deposits:number;withdrawals:number;cards:number;notifications:number}};
const money=(v:string|number,c:string)=>new Intl.NumberFormat('en-US',{style:'currency',currency:c}).format(Number(v||0));
const mask=(v:string)=>v.length>4?'•••• '+v.slice(-4):v;
export default function AdminCustomerDetailsPage(){
 const{id}=useParams<{id:string}>(); const[c,setC]=useState<Customer|null>(null); const[loading,setLoading]=useState(true); const[error,setError]=useState('');
 const[form,setForm]=useState({accountId:'',amount:'',reason:'',direction:'credit'}); const[blocks,setBlocks]=useState({transferBlocked:false,transferBlockMessage:'',withdrawalBlocked:false,withdrawalBlockMessage:''}); const[msg,setMsg]=useState('');
 async function load(){const r=await fetch('/api/v1/admin/customers/'+encodeURIComponent(id));const x=await r.json();if(!r.ok||!x.success)throw new Error(x.error||'Unable to load customer');setC(x.data);setBlocks({transferBlocked:x.data.transferBlocked,transferBlockMessage:x.data.transferBlockMessage||'',withdrawalBlocked:x.data.withdrawalBlocked,withdrawalBlockMessage:x.data.withdrawalBlockMessage||''});if(!form.accountId&&x.data.accounts[0])setForm(f=>({...f,accountId:x.data.accounts[0].id}));}
 useEffect(()=>{load().catch(e=>setError(e.message)).finally(()=>setLoading(false))},[id]);
 async function balance(e:React.FormEvent){e.preventDefault();setMsg('');const r=await fetch('/api/v1/admin/customers/'+encodeURIComponent(id),{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({action:'balance',...form})});const x=await r.json();if(!r.ok||!x.success)return setMsg(x.error||'Balance adjustment failed');setMsg('Balance adjustment completed.');await load();}
 async function saveBlocks(e:React.FormEvent){e.preventDefault();setMsg('');const r=await fetch('/api/v1/admin/customers/'+encodeURIComponent(id),{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({action:'transaction-blocks',...blocks})});const x=await r.json();if(!r.ok||!x.success)return setMsg(x.error||'Could not update restrictions');setMsg('Transaction restrictions updated.');await load();}
 if(loading)return <main className="mx-auto max-w-7xl px-4 py-8"><div className="h-8 w-56 animate-pulse rounded bg-slate-200"/><div className="mt-6 h-48 animate-pulse rounded-3xl bg-slate-200"/></main>;
 if(error||!c)return <main className="mx-auto max-w-2xl px-4 py-16"><div className="rounded-2xl bg-white p-10 text-center ring-1 ring-slate-200"><h1 className="text-xl font-bold">Customer unavailable</h1><p className="mt-2 text-sm text-slate-500">{error||'Customer not found'}</p><Link href="/admin/customers" className="mt-6 inline-flex rounded-xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white">Back to customers</Link></div></main>;
 return <main className="mx-auto max-w-7xl px-4 py-6 sm:px-6 sm:py-8"><div className="flex flex-wrap items-center justify-between gap-3"><div><Link href="/admin/customers" className="text-sm font-semibold text-indigo-700">← Customers</Link><h1 className="mt-2 text-3xl font-bold">{c.firstName} {c.lastName}</h1><p className="mt-1 text-sm text-slate-500">{c.email}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{c.status}</span></div>
 <section className="mt-6 grid gap-4 lg:grid-cols-2"><form onSubmit={balance} className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 className="text-xl font-bold">Adjust customer balance</h2><p className="mt-1 text-sm text-slate-500">Use the authoritative ledger. Every adjustment requires a reason.</p><select className="mt-5 input-field" value={form.accountId} onChange={e=>setForm({...form,accountId:e.target.value})}>{c.accounts.map(a=><option key={a.id} value={a.id}>•••• {a.accountNumber.slice(-4)} — {money(a.balance,a.currency)}</option>)}</select><select className="mt-3 input-field" value={form.direction} onChange={e=>setForm({...form,direction:e.target.value})}><option value="credit">Add balance</option><option value="debit">Remove balance</option></select><input className="mt-3 input-field" required placeholder="Amount" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><textarea className="mt-3 input-field min-h-24" required placeholder="Reason" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/><button className="mt-4 btn-primary w-full">Apply balance change</button></form>
 <form onSubmit={saveBlocks} className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 className="text-xl font-bold">Transaction restrictions</h2><p className="mt-1 text-sm text-slate-500">Block transfer/send money and withdrawals independently with a customer-facing message.</p><label className="mt-5 flex items-center gap-3 text-sm font-semibold"><input type="checkbox" checked={blocks.transferBlocked} onChange={e=>setBlocks({...blocks,transferBlocked:e.target.checked})}/>Block transfers / send money</label><textarea className="mt-3 input-field min-h-20" disabled={!blocks.transferBlocked} placeholder="Message shown to customer" value={blocks.transferBlockMessage} onChange={e=>setBlocks({...blocks,transferBlockMessage:e.target.value})}/><label className="mt-5 flex items-center gap-3 text-sm font-semibold"><input type="checkbox" checked={blocks.withdrawalBlocked} onChange={e=>setBlocks({...blocks,withdrawalBlocked:e.target.checked})}/>Block withdrawals</label><textarea className="mt-3 input-field min-h-20" disabled={!blocks.withdrawalBlocked} placeholder="Message shown to customer" value={blocks.withdrawalBlockMessage} onChange={e=>setBlocks({...blocks,withdrawalBlockMessage:e.target.value})}/><button className="mt-4 btn-primary w-full">Save restrictions</button>{msg&&<p className="mt-3 rounded-xl bg-slate-50 p-3 text-sm">{msg}</p>}</form></section>
 <section className="mt-6 grid gap-4 md:grid-cols-2">{c.accounts.map(a=><article key={a.id} className="rounded-3xl bg-slate-950 p-6 text-white"><p className="text-xs uppercase tracking-widest text-slate-400">{a.accountType}</p><p className="mt-3 text-3xl font-bold">{money(a.balance,a.currency)}</p><p className="mt-1 text-sm text-slate-400">Available {money(a.availableBalance,a.currency)}</p><p className="mt-6 font-mono text-sm">{mask(a.accountNumber)}</p><Link className="mt-4 inline-flex text-sm font-semibold text-indigo-300" href={'/admin/accounts?q='+encodeURIComponent(a.accountNumber)}>Open account →</Link></article>)}</section></main>;
}
